# Generated by Django 6.0.2 on 2026-03-11 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_studentevaluation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('department', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.AddField(
            model_name='abstract',
            name='coordinator1_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='abstract',
            name='coordinator2_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='groupevaluation',
            name='coordinator1_product_based',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupevaluation',
            name='coordinator1_research_oriented',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupevaluation',
            name='coordinator1_review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupevaluation',
            name='coordinator1_socially_relevant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupevaluation',
            name='coordinator1_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupevaluation',
            name='coordinator1_technical_exposure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupevaluation',
            name='coordinator2_product_based',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupevaluation',
            name='coordinator2_research_oriented',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupevaluation',
            name='coordinator2_review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupevaluation',
            name='coordinator2_socially_relevant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupevaluation',
            name='coordinator2_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupevaluation',
            name='coordinator2_technical_exposure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='coordinator1_interim',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='coordinator1_novelty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='coordinator1_planning',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='coordinator1_presentation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='coordinator1_scalability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='coordinator1_schedule',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='coordinator1_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='coordinator1_task_distribution',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='coordinator1_topic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='coordinator1_viva',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='coordinator2_interim',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='coordinator2_novelty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='coordinator2_planning',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='coordinator2_presentation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='coordinator2_scalability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='coordinator2_schedule',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='coordinator2_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='coordinator2_task_distribution',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='coordinator2_topic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='coordinator2_viva',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coordinatorapproval',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_approvals', to='core.group'),
        ),
        migrations.AlterUniqueTogether(
            name='coordinatorapproval',
            unique_together={('group', 'coordinator')},
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.class'),
        ),
        migrations.CreateModel(
            name='CoordinatorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_assignments', to=settings.AUTH_USER_MODEL)),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_assignments', to='core.class')),
            ],
            options={
                'unique_together': {('faculty', 'student_class')},
            },
        ),
    ]
