# Generated by Django 6.0.2 on 2026-03-11 13:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("core", "0025_remove_class_name_field"),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.AddField(
			model_name="studentevaluation",
			name="attendance_marks",
			field=models.IntegerField(
				blank=True,
				null=True,
				validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)],
			),
		),
		migrations.AddField(
			model_name="studentevaluation",
			name="attendance_submitted",
			field=models.BooleanField(default=False),
		),
		migrations.AddField(
			model_name="studentevaluation",
			name="attendance_submitted_at",
			field=models.DateTimeField(blank=True, null=True),
		),
		migrations.AddField(
			model_name="studentevaluation",
			name="attendance_submitted_by",
			field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="attendance_uploaded", to=settings.AUTH_USER_MODEL),
		),
	]