# Generated by Django 6.0.2 on 2026-03-11 14:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_studentevaluation_attendance_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("report_file", models.FileField(upload_to="project_reports/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("coordinator1_mark", models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ("coordinator2_mark", models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ("final_mark", models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ("coordinator1_submitted", models.BooleanField(default=False)),
                ("coordinator2_submitted", models.BooleanField(default=False)),
                ("group", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="project_report", to="core.group")),
                ("uploaded_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
