# Generated by Django 6.0.2 on 2026-03-11 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_projectreport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="projectreport",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectreport",
            name="rejected_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="rejected_project_reports", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="projectreport",
            name="rejection_review",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="projectreport",
            name="review_status",
            field=models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")], default="pending", max_length=12),
        ),
    ]
