# Generated by Django 6.0.2 on 2026-03-11 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_projectreport_rejection_workflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentevaluation",
            name="final_guide_mark",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentevaluation",
            name="final_guide_raw",
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)]),
        ),
        migrations.AddField(
            model_name="studentevaluation",
            name="final_guide_submitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentevaluation",
            name="final_guide_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
