# Generated by Django 6.0.2 on 2026-03-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_studentevaluation_final_guide_interim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentevaluation',
            name='cie_calculated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='cie_calculated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='cie_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='committee_mark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentevaluation',
            name='committee_raw_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
